export const environment = {
  production: false,

  firebase: {
    apiKey: '',
    authDomain: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
  },

  apiUrl: '',
  apiAbout: '',
  apiContactMe: '',
  apiEducation: '',
  apiEducationBulk: '',
  apiExperience: '',
  apiExperienceBulk: '',
  apiImage: '',
  apiUrlLogin: '',
  apiPasswordReset: '',
  apiUrlUser: '',
  apiAttachment: '',
  apiPersonal: '',
  apiPost: '',
  apiSocial: '',
  apiSkill: '',
  apiSkillsBulkUpdate: '',
  apiWork: '',
};
